### ISSUE TITLE
Gas spelling

### ISSUE THREAD

**Issue by xujiahuayz** [PiggyFinance/docs#16]
`GAS` in text should be replaced with `gas` (or `Gas` if it's the start of a sentence).

https://github.com/PiggyFinance/docs/blob/cd1912ffef7230073d1ff39bacbe284745394648/i18n/en/docusaurus-plugin-content-docs/current/protocol-algorithm-design.md?plain=1#L76

Please refer to the Chinese version:
https://github.com/PiggyFinance/docs/blob/master/i18n/zh/docusaurus-plugin-content-docs/current/protocol-algorithm-design.md

**Comment by jerrylib** [comment]
DONE
